### ISSUE TITLE
clang linker error patch

### ISSUE THREAD

**Issue by ric96** [khadas/android_manifest#1]
This source does't seem to have the following patch applied
[patch](https://android-review.googlesource.com/#/c/223100/1/core/clang/HOST_x86_common.mk)

which causes it to give the following errors
[error](https://paste.ubuntu.com/24070475/)

kindly concider updating the source

[UPDATE] i am still getting errors with this patch applied
[UPDATE 2] You need to run "make clean"  for this patch to take effect

**Comment by gouwa** [comment]
Thanks for the feedback, this patch works here also, and I will update soon.
