### ISSUE TITLE
target kvim3l-userdebug failure on ubuntu16.04

### ISSUE THREAD

**Issue by yf13** [khadas/android_manifest#4]
Hi,

I am building Android Pie for kvim3l device following the official docs. When building the "otapackage" I got the following error:

```
[ 62% 20327/32660] target Prebuilt: Chrome (out/target/product/kvim3l/obj/APPS/Chrome_intermediates/package.apk)
FAILED: out/target/product/kvim3l/obj/APPS/Chrome_intermediates/package.apk 
Unable to open 'out/target/product/kvim3l/obj/APPS/Chrome_intermediates/package.apk' for verification
Unable to open 'out/target/product/kvim3l/obj/APPS/Chrome_intermediates/package.apk.unaligned' as zip archive
mv: cannot stat 'out/target/product/kvim3l/obj/APPS/Chrome_intermediates/package.apk.aligned': No such file or directory
```
I checked the preinstalled Chrome package file ```device/khadas/kvim3l/preinstall/Chrome.apk```
and found it is a symbol link to ```device/khadas/kvim3/preinstall/Chrome.apk```, the latter is 
```
$ cat device/khadas/kvim3/preinstall/Chrome.apk
version https://git-lfs.github.com/spec/v1
oid sha256:19ebe3b7d3d3c315f5425dd739a9d31c195071656836a8806ccfb5033b17d019
size 132338434
```
I am wondering how this issue can be manually fixed so that I can restart another run?

**Comment by azureru** [comment]
I've encountered the same issue 
You need to make sure you install `git lfs` first - it's on the khadas doc

And then run 

```
cd device/khadas/
git lfs pull
```

**Comment by yf13** [comment]
Thanks for the prompt help.

Yes I have ```git lfs``` installed. But I didn't know that I need run the ```git lfs pull``` command as you mentioned. I did what you suggested and now the apk looks in normal size.

**Comment by yf13** [comment]
Thanks for the prompt reply! 
After ```git lfs pull```, I finally have the ```otapackage``` build works!
